export * from './courseTerms.service';
import { CourseTermsService } from './courseTerms.service';
export * from './courses.service';
import { CoursesService } from './courses.service';
export * from './grades.service';
import { GradesService } from './grades.service';
export * from './instructorCourseTerms.service';
import { InstructorCourseTermsService } from './instructorCourseTerms.service';
export * from './instructors.service';
import { InstructorsService } from './instructors.service';
export * from './nonModels.service';
import { NonModelsService } from './nonModels.service';
export * from './people.service';
import { PeopleService } from './people.service';
export * from './relationshipViews.service';
import { RelationshipViewsService } from './relationshipViews.service';
export * from './students.service';
import { StudentsService } from './students.service';
export const APIS = [CourseTermsService, CoursesService, GradesService, InstructorCourseTermsService, InstructorsService, NonModelsService, PeopleService, RelationshipViewsService, StudentsService];
