/**
 * myapp
 *
 * Contact: alan@columbia.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CourseTermsRelationShipsOneOf1Inner2 { 
    /**
     * The [type](https://jsonapi.org/format/#document-resource-object-identification) member is used to describe resource objects that share common attributes and relationships.
     */
    type: CourseTermsRelationShipsOneOf1Inner2.TypeEnum;
    /**
     * globally unique id (UUID4)
     */
    readonly id?: string;
}
export namespace CourseTermsRelationShipsOneOf1Inner2 {
    export type TypeEnum = 'grades';
    export const TypeEnum = {
        Grades: 'grades' as TypeEnum
    };
}


