/**
 * myapp
 *
 * Contact: alan@columbia.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Course1Data } from './course1Data';


/**
 * The identifier of the related object.
 */
export interface Course1 { 
    data: Course1Data;
}

