/**
 * myapp
 *
 * Contact: alan@columbia.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CourseTermAttributes } from './courseTermAttributes';
import { CourseTermTypeEnum } from './courseTermTypeEnum';
import { CourseTermRelationships } from './courseTermRelationships';


export interface CourseTerm { 
    /**
     * The [type](https://jsonapi.org/format/#document-resource-object-identification) member is used to describe resource objects that share common attributes and relationships.
     */
    type: CourseTermTypeEnum;
    attributes?: CourseTermAttributes;
    relationships?: CourseTermRelationships;
}
export namespace CourseTerm {
}


