/**
 * myapp
 *
 * Contact: alan@columbia.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CoursesRelationShipsOneOfInner } from './coursesRelationShipsOneOfInner';


/**
 * @type CoursesRelationShips
 * @export
 */
export type CoursesRelationShips = Array<CoursesRelationShipsOneOfInner>;

