/**
 * myapp
 *
 * Contact: alan@columbia.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CourseTermsRelationShipsOneOf1Inner { 
    /**
     * The [type](https://jsonapi.org/format/#document-resource-object-identification) member is used to describe resource objects that share common attributes and relationships.
     */
    type: CourseTermsRelationShipsOneOf1Inner.TypeEnum;
    readonly id?: number;
}
export namespace CourseTermsRelationShipsOneOf1Inner {
    export type TypeEnum = 'instructor_course_terms';
    export const TypeEnum = {
        InstructorCourseTerms: 'instructor_course_terms' as TypeEnum
    };
}


