/**
 * myapp
 *
 * Contact: alan@columbia.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Type21cEnum } from './type21cEnum';


export interface CourseTermsRelationShipsOneOf { 
    /**
     * The [type](https://jsonapi.org/format/#document-resource-object-identification) member is used to describe resource objects that share common attributes and relationships.
     */
    type: Type21cEnum;
    /**
     * globally unique id (UUID4)
     */
    readonly id?: string;
}
export namespace CourseTermsRelationShipsOneOf {
}


