/**
 * myapp
 *
 * Contact: alan@columbia.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CourseRelationships } from './courseRelationships';
import { Type21cEnum } from './type21cEnum';
import { CourseAttributes } from './courseAttributes';


export interface Course { 
    /**
     * The [type](https://jsonapi.org/format/#document-resource-object-identification) member is used to describe resource objects that share common attributes and relationships.
     */
    type: Type21cEnum;
    attributes?: CourseAttributes;
    relationships?: CourseRelationships;
}
export namespace Course {
}


