/**
 * myapp
 *
 * Contact: alan@columbia.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Person1 } from './person1';
import { CourseTerm } from './courseTerm';


export interface GradeRelationships { 
    course_term: CourseTerm;
    person: Person1;
}

