/**
 * myapp
 *
 * Contact: alan@columbia.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GradeAttributes { 
    /**
     * date when this instance becomes valid
     */
    effective_start_date?: string | null;
    /**
     * date when this instance becomes invalid
     */
    effective_end_date?: string | null;
    /**
     * who last modified this instance
     */
    readonly last_mod_user_name?: string | null;
    /**
     * when they modified it
     */
    readonly last_mod_date?: string;
    /**
     * Credits attempted/earned
     */
    credits: number;
    /**
     * * `None` - None * `A` - A * `B` - B * `C` - C * `D` - D * `F` - F * `P` - P
     */
    grade_letter?: GradeAttributes.GradeLetterEnum | null;
    /**
     * grade points (e.g. A is 4.0, F is 0.0)
     */
    grade_value?: number;
}
export namespace GradeAttributes {
    export type GradeLetterEnum = 'A' | 'B' | 'C' | 'D' | 'F' | 'P';
    export const GradeLetterEnum = {
        A: 'A' as GradeLetterEnum,
        B: 'B' as GradeLetterEnum,
        C: 'C' as GradeLetterEnum,
        D: 'D' as GradeLetterEnum,
        F: 'F' as GradeLetterEnum,
        P: 'P' as GradeLetterEnum
    };
}


