/**
 * myapp
 *
 * Contact: alan@columbia.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Instructor1Data } from './instructor1Data';


/**
 * The identifier of the related object.
 */
export interface Instructor1 { 
    data: Instructor1Data;
}

