/**
 * myapp
 *
 * Contact: alan@columbia.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InstructorsDataInner } from './instructorsDataInner';


/**
 * A related resource object from type instructors
 */
export interface Instructors { 
    data: Array<InstructorsDataInner>;
}

