/**
 * myapp
 *
 * Contact: alan@columbia.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type InstructorTypeEnum = 'instructors';

export const InstructorTypeEnum = {
    Instructors: 'instructors' as InstructorTypeEnum
};

