/**
 * myapp
 *
 * Contact: alan@columbia.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NonModelAttributes } from './nonModelAttributes';
import { NonModelTypeEnum } from './nonModelTypeEnum';


export interface NonModel { 
    /**
     * The [type](https://jsonapi.org/format/#document-resource-object-identification) member is used to describe resource objects that share common attributes and relationships.
     */
    type: NonModelTypeEnum;
    id: any | null;
    attributes?: NonModelAttributes;
}
export namespace NonModel {
}


