/**
 * myapp
 *
 * Contact: alan@columbia.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PatchedInstructorRequestData } from './patchedInstructorRequestData';


export interface PatchedInstructorRequest { 
    data: PatchedInstructorRequestData;
}

