/**
 * myapp
 *
 * Contact: alan@columbia.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CourseTermRequestDataAttributes } from './courseTermRequestDataAttributes';
import { CourseTermRelationships } from './courseTermRelationships';


export interface PatchedCourseTermRequestData { 
    /**
     * The [type](https://jsonapi.org/format/#document-resource-object-identification) member is used to describe resource objects that share common attributes and relationships.
     */
    type: PatchedCourseTermRequestData.TypeEnum;
    id: any | null;
    attributes?: CourseTermRequestDataAttributes;
    relationships?: CourseTermRelationships;
}
export namespace PatchedCourseTermRequestData {
    export type TypeEnum = 'course_terms';
    export const TypeEnum = {
        CourseTerms: 'course_terms' as TypeEnum
    };
}


