/**
 * myapp
 *
 * Contact: alan@columbia.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CourseRelationships } from './courseRelationships';
import { CourseRequestDataAttributes } from './courseRequestDataAttributes';


export interface PatchedCourseRequestData { 
    /**
     * The [type](https://jsonapi.org/format/#document-resource-object-identification) member is used to describe resource objects that share common attributes and relationships.
     */
    type: PatchedCourseRequestData.TypeEnum;
    id: any | null;
    attributes?: CourseRequestDataAttributes;
    relationships?: CourseRelationships;
}
export namespace PatchedCourseRequestData {
    export type TypeEnum = 'courses';
    export const TypeEnum = {
        Courses: 'courses' as TypeEnum
    };
}


