/**
 * myapp
 *
 * Contact: alan@columbia.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PeopleRelationShipsOneOfInner } from './peopleRelationShipsOneOfInner';
import { CourseTermsRelationShipsOneOf1Inner1 } from './courseTermsRelationShipsOneOf1Inner1';


/**
 * @type PeopleRelationShips
 * @export
 */
export type PeopleRelationShips = Array<CourseTermsRelationShipsOneOf1Inner1> | Array<PeopleRelationShipsOneOfInner>;

