/**
 * myapp
 *
 * Contact: alan@columbia.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Type18aEnum } from './type18aEnum';
import { PatchedPersonRequestDataRelationships } from './patchedPersonRequestDataRelationships';
import { PersonAttributes } from './personAttributes';


export interface Person { 
    /**
     * The [type](https://jsonapi.org/format/#document-resource-object-identification) member is used to describe resource objects that share common attributes and relationships.
     */
    type: Type18aEnum;
    attributes?: PersonAttributes;
    relationships?: PatchedPersonRequestDataRelationships;
}
export namespace Person {
}


