/**
 * myapp
 *
 * Contact: alan@columbia.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ResourceIdentifierData } from './resourceIdentifierData';


/**
 * The identifier of the related object.
 */
export interface ResourceIdentifier { 
    data: ResourceIdentifierData;
}

