/**
 * myapp
 *
 * Contact: alan@columbia.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ResourceIdentifier4Data } from './resourceIdentifier4Data';


/**
 * The identifier of the related object.
 */
export interface ResourceIdentifier4 { 
    data: ResourceIdentifier4Data;
}

