# Generated by Django 2.1.2 on 2018-10-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='last_mod_user_name',
            field=models.CharField(default=None, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='courseterm',
            name='last_mod_user_name',
            field=models.CharField(default=None, max_length=80, null=True),
        ),
    ]
