# Generated by Django 2.1.3 on 2018-11-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_unique_term_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseterm',
            name='term_identifier',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
