# Generated by Django 2.1.3 on 2018-12-05 20:48
# modified to move instructor.name into person.name

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20181205_1532'),
    ]

    def instr_name_to_person(apps, schema_editor):
        """
        Move the instructor name to person model.
        Creates a new person instance for each instructor.
        """
        Person = apps.get_model('myapp', 'Person')
        Instructor = apps.get_model('myapp', 'Instructor')
        for row in Instructor.objects.all():
            row.person = Person(name=row.name)
            row.save(update_fields=['person'])
            row.person.save()

    def person_name_to_instr(apps, schema_editor):
        """
        Move the person name to instructor model.
        """
        Person = apps.get_model('myapp', 'Person')
        Instructor = apps.get_model('myapp', 'Instructor')
        for row in Instructor.objects.all():
            row.name = row.person.name
            row.save(update_fields=['name'])

    operations = [
        # temporarily alter instructor.name to be nullable to enable reversing the migration.
        migrations.AlterField(
            model_name='instructor',
            name='name',
            field=models.CharField(db_column='instr_name', max_length=100, unique=True, null=True, default=None)
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='globally unique id (UUID4)', primary_key=True, serialize=False)),
                ('effective_start_date', models.DateField(blank=True, default=None, help_text='date when this model instance becomes valid', null=True)),
                ('effective_end_date', models.DateField(blank=True, default=None, help_text='date when this model instance becomes invalid', null=True)),
                ('last_mod_user_name', models.CharField(default=None, help_text='who last modified this instance', max_length=80, null=True)),
                ('last_mod_date', models.DateField(auto_now=True, help_text='when they modified it.')),
                ('name', models.CharField(db_column='person_name', max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'people',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='instructor',
            name='person',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to='myapp.Person'),
        ),
        migrations.RunPython(
            code=instr_name_to_person,
            reverse_code=person_name_to_instr,
        ),
        migrations.AlterModelOptions(
            name='instructor',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='name',
        ),
    ]
