# Generated by Django 3.1.6 on 2021-04-14 20:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20181206_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_description',
            field=models.TextField(help_text='Course description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_identifier',
            field=models.CharField(help_text='Course identifier (one-character suffix)', max_length=9, unique=True, validators=[django.core.validators.RegexValidator(regex='[A-Z]{4}[0-9]{4}[A-Z]'), django.core.validators.MinLengthValidator(limit_value=9)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(help_text='Course official title', max_length=80),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_number',
            field=models.CharField(help_text='"Shortcut" identifier (formerly for touch-tone registration)', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='effective_end_date',
            field=models.DateField(blank=True, default=None, help_text='date when this instance becomes invalid', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='effective_start_date',
            field=models.DateField(blank=True, default=None, help_text='date when this instance becomes valid', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='last_mod_date',
            field=models.DateField(auto_now=True, help_text='when they modified it'),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject_area_code',
            field=models.CharField(help_text='Subject', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='suffix_two',
            field=models.CharField(help_text='two-character identifier suffix', max_length=2),
        ),
        migrations.AlterField(
            model_name='courseterm',
            name='effective_end_date',
            field=models.DateField(blank=True, default=None, help_text='date when this instance becomes invalid', null=True),
        ),
        migrations.AlterField(
            model_name='courseterm',
            name='effective_start_date',
            field=models.DateField(blank=True, default=None, help_text='date when this instance becomes valid', null=True),
        ),
        migrations.AlterField(
            model_name='courseterm',
            name='last_mod_date',
            field=models.DateField(auto_now=True, help_text='when they modified it'),
        ),
        migrations.AlterField(
            model_name='courseterm',
            name='term_identifier',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(regex='[0-9]{4}[123][A-Z]{4}[0-9]{4}[A-Z]'), django.core.validators.MinLengthValidator(limit_value=14)]),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='effective_end_date',
            field=models.DateField(blank=True, default=None, help_text='date when this instance becomes invalid', null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='effective_start_date',
            field=models.DateField(blank=True, default=None, help_text='date when this instance becomes valid', null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='last_mod_date',
            field=models.DateField(auto_now=True, help_text='when they modified it'),
        ),
        migrations.AlterField(
            model_name='person',
            name='effective_end_date',
            field=models.DateField(blank=True, default=None, help_text='date when this instance becomes invalid', null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='effective_start_date',
            field=models.DateField(blank=True, default=None, help_text='date when this instance becomes valid', null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_mod_date',
            field=models.DateField(auto_now=True, help_text='when they modified it'),
        ),
    ]
