apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: myapp-gitlab
  description: Demo of Django REST Framework JSON-API
  annotations:
    backstage.io/techdocs-ref: 'url:https://gitlab.cc.columbia.edu/cuit-ent-arch/django-training'

  tags:
    - rest
spec:
  type: openapi
  lifecycle: development
  owner: alan@columbia.edu
  definition:
    $text: https://gitlab.cc.columbia.edu/cuit-ent-arch/django-training/raw/master/docs/schemas/openapi.yaml
