# Generated by Django 5.0.6 on 2024-05-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oauth", "0003_alter_myaccesstoken_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="myapplication",
            name="allowed_origins",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Allowed origins list to enable CORS, space separated",
            ),
        ),
        migrations.AddField(
            model_name="myapplication",
            name="hash_client_secret",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="myapplication",
            name="post_logout_redirect_uris",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Allowed Post Logout URIs list, space separated",
            ),
        ),
        migrations.AlterField(
            model_name="myaccesstoken",
            name="token",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
