# Generated by Django 5.0.7 on 2024-09-06 19:01

import oauth2_provider.models
from django.db import migrations, models
from oauth2_provider.settings import oauth2_settings

def forwards_func(apps, schema_editor):
    """
    Forward migration touches every "old" accesstoken.token which will cause the checksum to be computed.
    """
    AccessToken = apps.get_model(oauth2_settings.ACCESS_TOKEN_MODEL)
    accesstokens = AccessToken._default_manager.all()
    for accesstoken in accesstokens:
        accesstoken.save(update_fields=['token_checksum'])


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0004_myapplication_allowed_origins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myaccesstoken',
            name='token_checksum',
            field=oauth2_provider.models.TokenChecksumField(blank=True, max_length=64, ),
        ),
        migrations.AddField(
            model_name='myrefreshtoken',
            name='token_family',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='myaccesstoken',
            name='token',
            field=models.TextField(),
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='myaccesstoken',
            name='token_checksum',
            field=oauth2_provider.models.TokenChecksumField(blank=False, max_length=64,  db_index=True, unique=True),
        ),
    ]
